services:
  - type: web
    name: rems-app
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rems-db
          property: connectionString
      - key: SMTP_SERVER
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 465
      - key: SMTP_USERNAME
        value: emergencyrepairsmpet@gmail.com
      - key: SMTP_PASSWORD
        value: gvwe limw yzya oejc
      - key: EMAIL_FROM
        value: emergencyrepairsmpet@gmail.com
      - key: EMAIL_TO
        value: a.abdulrazzaq@medrepair.eu
      - key: UPLOAD_FOLDER
        value: uploads
      - key: PYTHON_VERSION
        value: 3.9.7

databases:
  - name: rems-db
    plan: free
    databaseName: rems
    user: rems_user

# Advanced properties (optional)
    pgExtensions:
      - pg_stat_statements
    ipAllowList:
      - 0.0.0.0/0
