# Render Configuration File
# Docs: https://render.com/docs/deploy-flask

services:
  - type: web
    name: rems-app
    runtime: python
    region: oregon  # or your preferred region
    
    # Build Commands
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      
    # Start Command
    startCommand: gunicorn app:app
    
    # Environment Variables
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rems-db
          property: connectionString
          
      - key: SMTP_SERVER
        value: smtp.gmail.com
        
      - key: SMTP_PORT
        value: 465
        
      - key: SMTP_USERNAME
        value: emergencyrepairsmpet@gmail.com
        
      - key: SMTP_PASSWORD
        sync: false  # Set this manually in dashboard
        
      - key: EMAIL_FROM
        value: emergencyrepairsmpet@gmail.com
        
      - key: EMAIL_TO
        value: a.abdulrazzaq@medrepair.eu
        
      - key: PYTHON_VERSION
        value: 3.9.13
    
    # Health Check
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: rems-db
    plan: free
    region: oregon  # Match web service region
    databaseName: rems_prod
    user: rems_user
    
    # PostgreSQL Extensions
    pgExtensions:
      - pg_stat_statements  # For performance monitoring
      
    # Security
    ipAllowList:
      - 0.0.0.0/0  # Allow all IPs (restrict for production)
